# -*- coding: utf-8 -*-
"""EXNO6-APPLIED DS.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oV8FwsiNkSKVxzMawlQPuHpGJ5YOjYa9
"""

import pandas as pd
import numpy as np

df=pd.read_csv('')

df

df.columns

df.isna().sum()

from fuzzywuzzy import process
from sklearn.preprocessing import MinMaxScaler

import dash
from dash import dcc, html
from dash.dependencies import Input, Output
import plotly.express as px
import pandas as pd

# INCLUDE YOUR CODE HERE